name: Build and publish documentation

on:
  push:
    branches: [ master ]

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt-get install libpoppler-cpp-dev libopenjp2-7-dev
        python -m pip install --upgrade pip
        pip install tox
    - name: Build docs
      run: tox -e docs
    - name: Publish docs
      run: git push -f "https://${GITHUB_ACTOR}:${{secrets.TOKEN}}@github.com/${GITHUB_REPOSITORY}.git" gh-pages:gh-pages
